In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import pprint as pp
import IPython
from IPython.display import display, HTML
from IPython.core.interactiveshell import InteractiveShell

InteractiveShell.ast_node_interactivity = "all"
CSS = """
.output {
    flex-direction: row;
}
"""
HTML('<style>{}</style>'.format(CSS))

In [2]:
def method_check(obj):
    a_list = []
    for method_name in dir(obj):
        if callable(getattr(obj, method_name)) & ~method_name.startswith('_'):
            a_list.append(method_name)
    return a_list

def attribute_check(obj):
    a_list = []
    for method_name in dir(obj):
        if callable(getattr(obj, method_name)) & method_name.startswith('_'):
            a_list.append(method_name)
    return a_list

ac = lambda x : print(IPython.utils.text.columnize(attribute_check(x)))
mc = lambda x : print(IPython.utils.text.columnize(method_check(x)))

---

## Cleaning/Mapping for tidy data.

Contained is primary dataset (`../0826export.csv`) which we will prepare for analysis. To help with this task we also have have another data set(`../store_master.xlsx`) which we will merge, map onto, and otherwise tidy up our primary dataset with.

In [37]:
df1 = pd.read_csv('./data_genesco/0826export.csv')
df1.columns = df1.columns.str.lower()

df2 = pd.read_excel('./data_genesco/store_master.xlsx')
df2.columns = df2.columns.str.lower()

In [39]:
# column creation and mapping
#############################
# store class column
df2_store_dict = dict(zip(df2['store'], df2['class']))
df1['class'] = df1['store'].map(df2_store_dict)

# store city column 
df2_city_dict = dict(zip(df2['store'], df2['store_city']))
df1['city'] = df1['store'].map(df2_city_dict)

# store state column
df2_state_dict = dict(zip(df2['store'], df2['store_state']))
df1['state'] = df1['store'].map(df2_state_dict)

# store close date
df2_closed_dict = dict(zip(df2['store'], df2['close_date']))
df1['close_date'] = df1['store'].map(df2_closed_dict)

df2_ft_dict = dict(zip(df2['store'], df2['gross_feet']))
df1['gross_feet'] = df1['store'].map(df2_ft_dict)

In [50]:
# df1.dtypes.value_counts()
df1.select_dtypes('O')
# df1.select_dtypes('int64')['fiscal_week']
# df1.select_dtypes('float64').columns

      week_end_date week_end_date_ly   class       city state close_date
0         06-FEB-16        07-FEB-15    Mall  LAS VEGAS    NV        NaN
1         13-FEB-16        14-FEB-15    Mall  LAS VEGAS    NV        NaN
2         20-FEB-16        21-FEB-15    Mall  LAS VEGAS    NV        NaN
3         27-FEB-16        28-FEB-15    Mall  LAS VEGAS    NV        NaN
4         05-MAR-16        07-MAR-15    Mall  LAS VEGAS    NV        NaN
5         12-MAR-16        14-MAR-15    Mall  LAS VEGAS    NV        NaN
6         19-MAR-16        21-MAR-15    Mall  LAS VEGAS    NV        NaN
7         26-MAR-16        28-MAR-15    Mall  LAS VEGAS    NV        NaN
8         02-APR-16        04-APR-15    Mall  LAS VEGAS    NV        NaN
9         09-APR-16        11-APR-15    Mall  LAS VEGAS    NV        NaN
10        16-APR-16        18-APR-15    Mall  LAS VEGAS    NV        NaN
11        23-APR-16        25-APR-15    Mall  LAS VEGAS    NV        NaN
12        30-APR-16        02-MAY-15    Mall  LAS VEGAS    NV        NaN
13        07-MAY-16        09-MAY-15    Mall  LAS VEGAS    NV        NaN
14        14-MAY-16        16-MAY-15    Mall  LAS VEGAS    NV        NaN
15        21-MAY-16        23-MAY-15    Mall  LAS VEGAS    NV        NaN
16        28-MAY-16        30-MAY-15    Mall  LAS VEGAS    NV        NaN
17        04-JUN-16        06-JUN-15    Mall  LAS VEGAS    NV        NaN
18        11-JUN-16        13-JUN-15    Mall  LAS VEGAS    NV        NaN
19        18-JUN-16        20-JUN-15    Mall  LAS VEGAS    NV        NaN
20        25-JUN-16        27-JUN-15    Mall  LAS VEGAS    NV        NaN
21        02-JUL-16        04-JUL-15    Mall  LAS VEGAS    NV        NaN
22        09-JUL-16        11-JUL-15    Mall  LAS VEGAS    NV        NaN
23        16-JUL-16        18-JUL-15    Mall  LAS VEGAS    NV        NaN
24        23-JUL-16        25-JUL-15    Mall  LAS VEGAS    NV        NaN
25        30-JUL-16        01-AUG-15    Mall  LAS VEGAS    NV        NaN
26        06-AUG-16        08-AUG-15    Mall  LAS VEGAS    NV        NaN
27        13-AUG-16        15-AUG-15    Mall  LAS VEGAS    NV        NaN
28        20-AUG-16        22-AUG-15    Mall  LAS VEGAS    NV        NaN
29        27-AUG-16        29-AUG-15    Mall  LAS VEGAS    NV        NaN
...             ...              ...     ...        ...   ...        ...
27163     05-JAN-19        06-JAN-18  Outlet   CHANDLER    AZ        NaN
27164     12-JAN-19        13-JAN-18  Outlet   CHANDLER    AZ        NaN
27165     19-JAN-19        20-JAN-18  Outlet   CHANDLER    AZ        NaN
27166     26-JAN-19        27-JAN-18  Outlet   CHANDLER    AZ        NaN
27167     02-FEB-19        03-FEB-18  Outlet   CHANDLER    AZ        NaN
27168     09-FEB-19        10-FEB-18  Outlet   CHANDLER    AZ        NaN
27169     16-FEB-19        17-FEB-18  Outlet   CHANDLER    AZ        NaN
27170     23-FEB-19        24-FEB-18  Outlet   CHANDLER    AZ        NaN
27171     02-MAR-19        03-MAR-18  Outlet   CHANDLER    AZ        NaN
27172     09-MAR-19        10-MAR-18  Outlet   CHANDLER    AZ        NaN
27173     16-MAR-19        17-MAR-18  Outlet   CHANDLER    AZ        NaN
27174     23-MAR-19        24-MAR-18  Outlet   CHANDLER    AZ        NaN
27175     30-MAR-19        31-MAR-18  Outlet   CHANDLER    AZ        NaN
27176     06-APR-19        07-APR-18  Outlet   CHANDLER    AZ        NaN
27177     13-APR-19        14-APR-18  Outlet   CHANDLER    AZ        NaN
27178     27-APR-19        28-APR-18  Outlet   CHANDLER    AZ        NaN
27179     04-MAY-19        05-MAY-18  Outlet   CHANDLER    AZ        NaN
27180     11-MAY-19        12-MAY-18  Outlet   CHANDLER    AZ        NaN
27181     18-MAY-19        19-MAY-18  Outlet   CHANDLER    AZ        NaN
27182     25-MAY-19        26-MAY-18  Outlet   CHANDLER    AZ        NaN
27183     01-JUN-19        02-JUN-18  Outlet   CHANDLER    AZ        NaN
27184     08-JUN-19        09-JUN-18  Outlet   CHANDLER    AZ        NaN
27185     15-JUN-19        16-JUN-18  Outlet   CHANDLER    AZ        NaN
27186     22-JUN-19        23-JUN-18  Outlet   CHANDLER    AZ        NaN
27187     29-JUN-19        30-JUN-18  Outlet   CHANDLER    AZ        NaN
27188     06-JUL-19        07-JUL-18  Outlet   CHANDLER    AZ        NaN
27189     13-JUL-19        14-JUL-18  Outlet   CHANDLER    AZ        NaN
27190     20-JUL-19        21-JUL-18  Outlet   CHANDLER    AZ        NaN
27191     27-JUL-19        28-JUL-18  Outlet   CHANDLER    AZ        NaN
27192     03-AUG-19        04-AUG-18  Outlet   CHANDLER    AZ        NaN

[27193 rows x 6 columns]

109

In [5]:
# df_closed
df_closed = df1[df1['close_date'].notnull()].drop('div', axis=1)
# df_closed = df_closed.groupby(['store','fiscal_year','fiscal_month'])['comp_pct']
# df_closed = df_closed.groupby('store')
# df_closed.head()
df_closed['week_end_date'] = df_closed['week_end_date'].apply(lambda x: pd.to_datetime(x))

---

## Selecing Column Variables for doing a correlation

In [274]:
# new = closed_stripped_df.groupby(['store','fiscal_year'])['comp_pct'].mean().unstack().reset_index()
# new = closed_stripped_df.groupby(['store','fiscal_year']).sum()
# new = df_closed[:, [1,3,8,15,16,17,18,19,20, 27,28,29,30,31,32,33,34,35,36,55,56,57,58,59,60,61,
#                    62,63,64,65,66,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,99,
#                   100,101,102,103,104,105,106,107,108]]

# df_closed

---

## Grouping TEST CELL BELOW

In [ ]:

####################################
####################################

# df_pivot = df1.pivot_table(values='comp_pct', index=['store'],columns='fiscal_year')#.nlargest(10, 'fiscal_year')
# df_pivot['comp_pct_sum'] = df_pivot[2017] + df_pivot[2018] + df_pivot[2019] + df_pivot[2020]
# df_pivot.nsmallest(10, 'comp_pct_sum')
    
    
####################################
####################################

# df1.groupby('store')['comp_pct'].sum().nsmallest(10)
# df1[['gross_feet', 'comp_pct']].groupby('comp_pct')['gross_feet'].value_counts(bins=20)#.plot(kind='scatter');
# df1[['gross_feet', 'comp_pct']].groupby('gross_feet').mean().hist(bins=40);

In [130]:
# grouped_class_comp_sum = df1.groupby(['class'])['comp_pct'].sum() # keep these
# grouped_class_comp_mean = df1.groupby(['class'])['comp_pct'].mean() # keep these

# grouped_store_comp_sum = df1.groupby(['store'])['comp_pct'].sum() # keep these
# grouped_store_comp_mean = df1.groupby(['store'])['comp_pct'].mean() # keep these

grouped_store = df_closed.groupby(['fiscal_year','store'])[['comp_pct', 
                                                            'strak_transaction_num', 
                                                            'tot_avg_tenure_days','city',
                                                            'state','gross_feet']].sum()
# grouped_city_comp_sum.nlargest(10)
# grouped_class_comp_sum.nlargest(10)

# grouped_store.index
grouped_store.xs((2017, 1643), axis=0)

comp_pct                    -8.341135
strak_transaction_num     3561.000000
tot_avg_tenure_days       4206.000000
gross_feet               43378.000000
Name: (2017, 1643), dtype: float64

In [69]:
# grouped_store_comp_mean.nsmallest(10)
# grouped_store_comp_sum.nsmallest(10)
# mc(pd.core.groupby.generic.DataFrameGroupBy)
dir(grouped_store.index)

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_priority__',
 '__array_wrap__',
 '__bool__',
 '__bytes__',
 '__class__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getslice__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__init__',
 '__init_subclass__',
 '__inv__',
 '__isub__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mod__',
 '__module__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__nonzero__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rfloordiv__',
 '__rmul__',
 '__rpow__',
 '__rsub__',
 '__rtruediv__',
 '__setattr__',
 '__setitem__',
 '__setstate__',
 '__sizeof__',
 '__str__',
 '__sub__',
 '__subclasshook__',
 '__truediv__',
 '__unicode__',
 '__weakref__',
 '__xor__',
 '_accessors',
 '_add_comparison_methods',
 '_add_logical_methods',
 '_add_logical_methods_disabled',
 '_add_numeric_methods',
 '_add_numeric_methods_add_sub_disabled',
 '_add_numeric_methods_binary',
 '_add_numeric_methods_disabled',
 '_add_numeric_methods_unary',
 '_assert_can_do_op',
 '_assert_can_do_setop',
 '_assert_take_fillable',
 '_attributes',
 '_can_hold_identifiers_and_holds_name',
 '_can_hold_na',
 '_can_reindex',
 '_cleanup',
 '_codes',
 '_coerce_scalar_to_index',
 '_coerce_to_ndarray',
 '_comparables',
 '_concat',
 '_concat_same_dtype',
 '_constructor',
 '_convert_arr_indexer',
 '_convert_can_do_setop',
 '_convert_for_op',
 '_convert_index_indexer',
 '_convert_list_indexer',
 '_convert_listlike_indexer',
 '_convert_scalar_indexer',
 '_convert_slice_indexer',
 '_convert_tolerance',
 '_data',
 '_defer_to_indexing',
 '_deprecations',
 '_dir_additions',
 '_dir_deletions',
 '_drop_from_level',
 '_engine',
 '_engine_type',
 '_evaluate_with_datetime_like',
 '_evaluate_with_timedelta_like',
 '_filter_indexer_tolerance',
 '_format_attrs',
 '_format_data',
 '_format_native_types',
 '_format_space',
 '_format_with_header',
 '_formatter_func',
 '_get_attributes_dict',
 '_get_codes_for_sorting',
 '_get_fill_indexer',
 '_get_fill_indexer_searchsorted',
 '_get_grouper_for_level',
 '_get_level_indexer',
 '_get_level_number',
 '_get_level_values',
 '_get_loc_only_exact_matches',
 '_get_names',
 '_get_nearest_indexer',
 '_get_reconciled_name_object',
 '_get_string_slice',
 '_get_unique_index',
 '_has_complex_internals',
 '_hashed_indexing_key',
 '_hashed_values',
 '_have_mixed_levels',
 '_id',
 '_infer_as_myclass',
 '_inferred_type_levels',
 '_inner_indexer',
 '_invalid_indexer',
 '_is_homogeneous_type',
 '_is_memory_usage_qualified',
 '_is_numeric_dtype',
 '_is_strictly_monotonic_decreasing',
 '_is_strictly_monotonic_increasing',
 '_isnan',
 '_join_level',
 '_join_monotonic',
 '_join_multi',
 '_join_non_unique',
 '_join_precedence',
 '_left_indexer',
 '_left_indexer_unique',
 '_levels',
 '_map_values',
 '_maybe_cast_indexer',
 '_maybe_cast_slice_bound',
 '_maybe_promote',
 '_maybe_update_attributes',
 '_mpl_repr',
 '_na_value',
 '_names',
 '_nan_idxs',
 '_nbytes',
 '_ndarray_values',
 '_outer_indexer',
 '_partial_tup_index',
 '_reduce',
 '_reindex_non_unique',
 '_reset_cache',
 '_reset_identity',
 '_scalar_data_error',
 '_searchsorted_monotonic',
 '_set_codes',
 '_set_levels',
 '_set_names',
 '_shallow_copy',
 '_shallow_copy_with_infer',
 '_simple_new',
 '_sort_levels_monotonic',
 '_string_data_error',
 '_summary',
 '_to_safe_for_reshape',
 '_try_convert_to_int_index',
 '_tuples',
 '_typ',
 '_unpickle_compat',
 '_update_inplace',
 '_validate_for_numeric_binop',
 '_validate_for_numeric_unaryop',
 '_validate_index_level',
 '_validate_indexer',
 '_validate_names',
 '_validate_sort_keyword',
 '_values',
 '_verify_integrity',
 '_wrap_joined_index',
 '_wrap_setop_result',
 'all',
 'any',
 'append',
 'argmax',
 'argmin',
 'argsort',
 'array',
 'asi8',
 'asof',
 'asof_locs',
 'astype',
 'codes',
 'contains',
 'copy',
 'delete',
 'difference',
 'drop',
 'drop_duplicates',
 'droplevel',
 'dropna',
 'dtype',
 'dtype_str',
 'duplicated',
 'empty',
 'equal_levels',
 'equals',
 'factorize',
 'fillna',
 'format',
 'from_arrays',
 'from_frame',
 'from_product',
 'from_tuples',
 'get_duplicates',
 'get_indexer',
 'get_indexer_for',
 'get_indexer_non_unique',
 'get_level_values',
 'get_loc',
 'get_loc_level',
 'get_locs',
 'get_slice_bound',
 'get_value',
 'get_values',
 'groupby',
 'has_duplicates',
 'hasnans',
 'holds_integer',
 'identical',
 'inferred_type',
 'insert',
 'intersection',
 'is_',
 'is_all_dates',
 'is_boolean',
 'is_categorical',
 'is_floating',
 'is_integer',
 'is_interval',
 'is_lexsorted',
 'is_lexsorted_for_tuple',
 'is_mixed',
 'is_monotonic',
 'is_monotonic_decreasing',
 'is_monotonic_increasing',
 'is_numeric',
 'is_object',
 'is_type_compatible',
 'is_unique',
 'isin',
 'isna',
 'isnull',
 'item',
 'join',
 'labels',
 'levels',
 'levshape',
 'lexsort_depth',
 'map',
 'max',
 'memory_usage',
 'min',
 'name',
 'names',
 'nbytes',
 'ndim',
 'nlevels',
 'notna',
 'notnull',
 'nunique',
 'putmask',
 'ravel',
 'reindex',
 'remove_unused_levels',
 'rename',
 'reorder_levels',
 'repeat',
 'searchsorted',
 'set_codes',
 'set_labels',
 'set_levels',
 'set_names',
 'set_value',
 'shape',
 'shift',
 'size',
 'slice_indexer',
 'slice_locs',
 'sort',
 'sort_values',
 'sortlevel',
 'summary',
 'swaplevel',
 'symmetric_difference',
 'take',
 'to_flat_index',
 'to_frame',
 'to_hierarchical',
 'to_list',
 'to_native_types',
 'to_numpy',
 'to_series',
 'transpose',
 'truncate',
 'union',
 'unique',
 'value_counts',
 'values',
 'view',
 'where']

In [ ]:
grouped_store_pct_largest = df1.groupby(['store'])['comp_pct', 
                                          'accessory_units',
                                          'trans_cnt_sales',
                                          'trans_cnt_total',
                                          'accessory_units'].sum().nlargest(10, 'comp_pct')

grouped_store_pct_smallest = df1.groupby(['store'])['comp_pct', 
                                          'accessory_units',
                                          'trans_cnt_sales',
                                          'trans_cnt_total',
                                          'accessory_units'].sum().nsmallest(10, 'comp_pct')

In [ ]:
# grouped_store_pct_largest.corr()
# grouped_store_pct_smallest.corr()

In [ ]:
# grouped_store_pct_largest
# grouped_store_pct_smallest

In [401]:
grouped_store_pct_smallest = df1.groupby(['store'])['comp_pct', 
                                          'accessory_units',
                                          'trans_cnt_sales',
                                          'trans_cnt_total',
                                          'accessory_units'].sum()

grouped_store_pct_smallest.nsmallest(10, 'comp_pct')

,comp_pct,accessory_units,trans_cnt_sales,trans_cnt_total,accessory_units
store,,,,,
1643,-13.529220,6449,5682,6763,6449
1803,-12.364402,17716,10311,12015,17716
1817,-11.544135,29302,14335,16638,29302
1600,-10.686017,13721,12220,14429,13721
2067,-8.856854,29207,16848,18444,29207
1717,-7.597681,21186,12396,12850,21186
1504,-6.772227,27988,14272,15371,27988
1849,-6.053967,4412,3127,3912,4412
1672,-4.967440,14585,10132,12204,14585
1854,-4.891813,73684,39649,44854,73684